### ISSUE TITLE
Segmentation Fault

### ISSUE THREAD

**Issue by Rikeard** [ViniciusLuciano/ED#1]
O código apresentou Segmentation Fault e não completou a execução nos casos
```
./siguel -e ../src/input -f b1.geo -q b1/-brl-all.qry 
Segmentation fault (core dumped)

./siguel -e ../src/input -f b1.geo -q b1/-mix2.qry 
Segmentation fault (core dumped)

./siguel -e ../src/input -f b1.geo -q b1/-mix1.qry 
Segmentation fault (core dumped)

./siguel -e ../src/input -f b1.geo -q b1/-brl-5.qry 
Segmentation fault (core dumped)
```

**Comment by ViniciusLuciano** [comment]
Isso devia-se ao caso no qual o elemento da lista deletado era ao mesmo tempo o primeiro e o ultimo da lista. Correção realizada no commit [Correção deletar lista e refatoração de partes do codigo ](https://github.com/ViniciusLuciano/ED/commit/f143f5f75c0e607da72f1c461f6664a52ecf8c27)
